version: 0.0
os: linux
files:
  - source: /
    destination: /opt/myapp

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 120
      runas: root
    - location: scripts/delete_existing_file.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 120
      runas: root

