apiVersion: apps/v1
kind: Deployment
metadata:
  name: gugu-bank-deployment
  namespace: gu9duck
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gugu-bank
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gugu-bank
      annotations:
        sidecar.istio.io/inject: "true" # Istio sidecar 주입
    spec:
      containers:
        - name: gugu-bank-container
          image: sungue/gugu-bank:090b65b1c381c6e9842d76ec571e30c24b3e033f
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://172.30.1.87:30879/mydatabase # MySQL 서비스와 연결1
            - name: SPRING_DATASOURCE_USERNAME
              value: root # MySQL 사용자 이름
            - name: SPRING_DATASOURCE_PASSWORD
              value: Gu9duck # MySQL 비밀번호
            - name: REDIS_HOST
              value: "my-redis-master.gu9duck.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-redis
                  key: redis-password
          resources:  # 리소스 요청 및 제한 추가
            requests:
              cpu: "100m"  # 요청 CPU
              memory: "128Mi"  # 요청 메모리
            limits:
              cpu: "200m"  # 제한 CPU
              memory: "256Mi"  # 제한 메모리