apiVersion: apps/v1
kind: Deployment
metadata:
  name: gugu-bank-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gugu-bank
  template:
    metadata:
      labels:
        app: gugu-bank
    spec:
      containers:
        - name: gugu-bank-container
          image: insav/gugu-bank:3
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "gu9duck.cbmgicamgfgg.ap-northeast-1.rds.amazonaws.com" # RDS 호스트 이름
            - name: DB_PORT
              value: "3306" # MySQL 포트
            - name: DB_USER
              value: "admin" # MySQL 사용자 이름
            - name: DB_PASSWORD
              value: "guguduck" # MySQL 비밀번호
            - name: DB_NAME
              value: "gu9duck" # 데이터베이스 이름
