apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
spec:
  selector:
    istio: ingressgateway # Istio의 IngressGateway 사용함
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
