name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      deployments: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      DOCKER_IMAGE: insav/gugu-bank:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE .

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          kubectl --kubeconfig=kubeconfig.yaml get nodes

      - name: Output kubeconfig content
        run: cat kubeconfig.yaml

      - name: Update Argo CD application
        run: |
          argocd login a2448034a5e1f4ff796af814926572ff-1664569724.ap-northeast-1.elb.amazonaws.com --username admin --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync gu9duck-bank
          argocd app wait gu9duck-bank --timeout 150
