name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_IMAGE: sungue/gugu-bank:${{ github.sha }} # SHA 기반 이미지 사용12

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      deployments: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE .
        run: docker build -t $DOCKER_IMAGE .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_IMAGE

      - name: Update image tag in values file
        run: |
          sed -i "s|image: sungue/gugu-bank:.*|image: sungue/gugu-bank:${{ github.sha }}|g" ./scripts/bankDeplo.yaml
      - name: Commit changes
        run: |
          git config --global user.email "sungue4098@naver.com" 
          git config --global user.name "sungue1" 
          git config --global user.email "sungue4098@naver.com" 
          git config --global user.name "sungue1" 
          git add ./scripts/bankDeplo.yaml
          git commit -m "Update image to use GitHub SHA"
          git push
      - name: Install Argo CD CLI
        run: |
          curl -sSL https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 -o argocd
          sudo install -m 0755 argocd /usr/local/bin/argocd
      - name: Update Argo CD application
        run: |
          argocd login a2448034a5e1f4ff796af814926572ff-1664569724.ap-northeast-1.elb.amazonaws.com --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
          argocd app sync gu9duck-bank --force
          argocd app wait gu9duck-bank --timeout 150
