name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop
      - feature/login
      - feature/login-security
      - feature/login-session
      - feature-main
  pull_request:
    branches:
      - main
      - develop
      - feature/login
      - feature/login-security
      - feature/login-session
      - feature-main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      CODE_DEPLOY_APP_NAME: gu9duck-codedeploy
      S3_BUCKET_NAME: gu9duck.lion2.nyhhs.com

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Set up GitHub Packages in settings.xml
      run: |
        echo "<settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>" > $GITHUB_WORKSPACE/settings.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DaltDeploymentRepository=github::https://maven.pkg.github.com/HZion/java_bank
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-northeast-1'

    - name: Remove carriage return characters from scripts
      run: |
        sed -i 's/\r//g' scripts/*.sh

    - name: Zip files for deployment
      run: zip -r myapp-deployment.zip target/bank-0.0.1-SNAPSHOT.jar appspec.yml scripts/before_install.sh scripts/stop_application.sh scripts/delete_existing_file.sh 

    - name: Upload to S3
      run: aws s3 cp myapp-deployment.zip s3://$S3_BUCKET_NAME/ 

    - name: Code Deploy
      run: |
        aws deploy create-deployment \
          --application-name $CODE_DEPLOY_APP_NAME \
          --deployment-group-name gu9duck-codedeploy-group \
          --s3-location bucket=$S3_BUCKET_NAME,key=myapp-deployment.zip,bundleType=zip \
          --deployment-config-name CodeDeployDefault.AllAtOnce
